CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE entry (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "dev-name" text NOT NULL,
    date date NOT NULL,
    "starting-time" text NOT NULL,
    "ending-time" text NOT NULL,
    comment text NOT NULL,
    CONSTRAINT "PK_entry" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240328172737_InitialCreate', '8.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE entry ADD "total-time" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240403130811_AddedNewColumn', '8.0.3');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240404173453_UpdatedAppSettings', '8.0.3');

COMMIT;

