CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "user" (
    "user-id" integer GENERATED BY DEFAULT AS IDENTITY,
    user_name text NOT NULL,
    password text NOT NULL,
    CONSTRAINT "PK_user" PRIMARY KEY ("user-id")
);

CREATE TABLE entry (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "dev-name" text NOT NULL,
    date date NOT NULL,
    "starting-time" text NOT NULL,
    "ending-time" text NOT NULL,
    comment text NOT NULL,
    "total-time" text NOT NULL,
    "user-id" integer NOT NULL,
    CONSTRAINT "PK_entry" PRIMARY KEY (id),
    CONSTRAINT "FK_entry_user_user-id" FOREIGN KEY ("user-id") REFERENCES "user" ("user-id") ON DELETE CASCADE
);

CREATE INDEX "IX_entry_user-id" ON entry ("user-id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240409141434_InitialCreate', '8.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE entry ALTER COLUMN "total-time" DROP NOT NULL;

ALTER TABLE entry ALTER COLUMN "starting-time" DROP NOT NULL;

ALTER TABLE entry ALTER COLUMN "ending-time" DROP NOT NULL;

ALTER TABLE entry ALTER COLUMN "dev-name" DROP NOT NULL;

ALTER TABLE entry ALTER COLUMN date TYPE text;
ALTER TABLE entry ALTER COLUMN date DROP NOT NULL;

ALTER TABLE entry ALTER COLUMN comment DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240409203501_UpdatedEntity', '8.0.3');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240410191057_UpdatedEntryEntity', '8.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE entry RENAME COLUMN "dev-name" TO "user-name";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240411115031_AddedUsernamecolumn', '8.0.3');

COMMIT;

