// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pomodoro.Server.DbContexts;

#nullable disable

namespace Pomodoro.Server.Migrations
{
    [DbContext(typeof(EntryDbContext))]
    [Migration("20240403130811_AddedNewColumn")]
    partial class AddedNewColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pomodoro.Server.Models.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Devname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dev-name");

                    b.Property<string>("Endingtime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ending-time");

                    b.Property<string>("Startingtime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("starting-time");

                    b.Property<string>("Totaltime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("total-time");

                    b.HasKey("Id");

                    b.ToTable("entry");
                });
#pragma warning restore 612, 618
        }
    }
}
