jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x
      - name: Restore dependency
        run: dotnet restore Pomodoro.Server
      - name: Build project
        run: dotnet build -c Release --no-restore Pomodoro.Server
      - name: publish project
        run: dotnet publish Pomodoro.Server -c Release -o ./publish
      - name: Make Key Read only Step 1
        run: pwd 

      
      
     
name: Build and Test
'on':
  push:
    branches:
      - main

