name: CI-CD
'on':
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x
      - name: Restore dependency
        run: dotnet restore Pomodoro.Server
      - name: Build project
        run: dotnet build -c Release --no-restore Pomodoro.Server
      - name: publish project
        run: dotnet publish Pomodoro.Server -c Release -o ./publish
      - name: Make Key Read only Step 1
        run: pwd 
      - name: Make Key Read only Step 2
        run: sudo chmod 0400 /home/runner/work/pomodoroSC/pomodoroSC/key/ls-rywds-dev-01-keypair-01.pem
      - name: Make Key Read only Step 3 - Verify
        run: pwd && ls -al /home/runner/work/pomodoroSC/pomodoroSC/key
      - name: Install SSH
        run: sudo apt-get install openssh-client -y
      - name: Create Server Target Folder
        run: ssh -o StrictHostKeyChecking=no -i /home/runner/work/pomodoroSC/pomodoroSC/key/ls-rywds-dev-01-keypair-01.pem  ubuntu@3.213.39.34 'mkdir -p /usr/lknsln/devscapps/pomodoro/$(date +"%Y%m%d%H%M")'
      - name: Copy Server files to EC2 instance
        run: scp -o StrictHostKeyChecking=no -r -i /home/runner/work/pomodoroSC/pomodoroSC/key/ls-rywds-dev-01-keypair-01.pem ./publish/* 'ubuntu@3.213.39.34:/usr/lknsln/devscapps/pomodoro/$(date +"%Y%m%d%H%M")'
      - name: Remove a SymLink 
        run: ssh -o StrictHostKeyChecking=no -i /home/runner/work/pomodoroSC/pomodoroSC/key/ls-rywds-dev-01-keypair-01.pem  ubuntu@3.213.39.34 ' rm /usr/lknsln/devscapps/pomodoro/current'
      - name: Print Current Working Directory
        run: pwd 
      - name: Create a SymLink
        run: ssh -o StrictHostKeyChecking=no -i /home/runner/work/pomodoroSC/pomodoroSC/key/ls-rywds-dev-01-keypair-01.pem  ubuntu@3.213.39.34 'ln -s /usr/lknsln/devscapps/pomodoro/$(date +"%Y%m%d%H%M") current'
      - name: Create a service 
        run:  ssh -o StrictHostKeyChecking=no -i /home/runner/work/pomodoroSC/pomodoroSC/key/ls-rywds-dev-01-keypair-01.pem  ubuntu@3.213.39.34 echo"Test001" > $(date +"%Y%m%d%H%M").service && nano -S -x $(date +"%Y%m%d%H%M").service'
      
